version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    commit-message:
      prefix: "chore"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10
