name: Lint

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}-new

    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    - name: Run ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
