name: Lint

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Yarn modules
      uses: actions/cache@v2
      with:
        path: ~/.yarn-cache
        key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}-new

    - name: Install Dependencies
      run: yarn install

    - name: Run ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
