name: Lint and Formatting

on: [pull_request]

jobs:
  eslint_and_prettier:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: yarn install

    - name: Check Code Format
      run: npx prettier --check .

    - name: Run ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
