name: Prettier Code Formatter

on: [pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Yarn modules
        uses: actions/cache@v2
        with:
          path: ~/.yarn-cache
          key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}-new

      - name: Install Dependencies
        run: yarn install

      - name: Check Code Format
        run: npx prettier --check .
